name: ble-test
version: git
summary: Bluetooth test
description: |
  Bluetooth test

grade: devel
confinement: devmode

parts:
  ble-test:
    source: .
    plugin: go
    go-importpath: github.com/RobHumphris/ble-test

apps:
  ble-test:
    command: ble-test